### ISSUE TITLE
order update

### ISSUE THREAD

**Issue by vyaspranjal33** [ryanburgess/2018-conferences#65]
events should be ordered by "CHRONOLOGICAL" @ryanburgess

**Comment by CHEWX** [comment]
Unfortunately due to the way people populate the JSON file, the JSON file acts as the API. So it's not really enforceable.

As such, the README that is generated is done so in chronological order, and if you wish to use the API for a PHP list for example, it's easy enough to do it server side rather than making the API itself in the correct order.

It's too much to ask for an open-source API in my opinion and makes no difference to it anyway as it's easy to sort if you are using for another application.

Would love to know what you use-case is for this issue being raised? The only thing I can think of is when you want to add a new event you want to see if it's already in the list, and if that's the case I would advise taking a look at the auto generated README :)

**Comment by vyaspranjal33** [comment]
ok @CHEWX
